### ISSUE TITLE
Meta Info for page fixes

### ISSUE THREAD

**Issue by nightmaregaurav** [nightmaregaurav/personal-website-cms-source#17]
- [x] Default meta tags for all pages individually, use relevant titles and descriptions, images, and SEO-friendly keywords, use the default if not available. (ex: use 'Created with personal-website-cms' for description).
- [x] Remove user-provided meta tags feature.
- [x] Automatic META info of projects in project pages.
